import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

export default function Header () {
  const [token, setToken] = useState('')
  const router = useRouter()

  useEffect(() => {
    const sToken = window.sessionStorage.getItem('token')
    setToken(sToken)
  }, [])
  const handleLogOut = evt => {
    evt.preventDefault()
    evt.stopPropagation()

    window.sessionStorage.setItem('token', '')
    router.push('/')
  }
  return (
    <>
      <Head>
        <title>My Awesome Ucamp eCommerce</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>


      <nav className='navbar is-transparent' role='navigation' aria-label='main navigation'>
        <div className='navbar-brand'>
          <a className='navbar-item' href='https://bulma.io'>
            <img src='https://bulma.io/images/bulma-logo.png' width='112' height='28' />
          </a>

          <a role='button' className='navbar-burger' aria-label='menu' aria-expanded='false' data-target='navbarBasicExample'>
            <span aria-hidden='true'></span>
            <span aria-hidden='true'></span>
            <span aria-hidden='true'></span>
          </a>
        </div>

        <div id='navbarBasicExample' className='navbar-menu'>
          <div className='navbar-start'>
            <a className='navbar-item'>
              Home
            </a>

            <a className='navbar-item'>
              Documentation
            </a>

            <div className='navbar-item has-dropdown is-hoverable'>
              <a className='navbar-link'>
                More
              </a>

              <div className='navbar-dropdown'>
                <a className='navbar-item'>
                  About
                </a>
                <a className='navbar-item'>
                  Jobs
                </a>
                <a className='navbar-item'>
                  Contact
                </a>
                <hr className='navbar-divider' />
                <a className='navbar-item'>
                  Report an issue
                </a>
              </div>
            </div>
          </div>

          <div className='navbar-end'>
            <div className='navbar-item'>
              <div className='buttons'>
                {!token && (
                  <>
                    <a className='button is-primary'>
                      <strong>Sign up</strong>
                    </a>
                    <a className='button is-light'>
                      Log in
                    </a>
                  </>
                )}

                {token && (
                  <a className='button is-light' onClick={e => handleLogOut(e)}>
                    Log out
                  </a>
                )}
              </div>
            </div>
          </div>
        </div>
      </nav>
    </>
  )
}
